### ISSUE TITLE
App does not work with safari 

### ISSUE THREAD

**Issue by saf6260** [all-rit/AccessibilityLab2#13]
**Describe the bug**
Colored circles are not appearing on safari as well as color vision deficiencies are not being simulated properly on safari

**To Reproduce**
Assign up to 10 people to this issue
￼
Filter people
￼
saf6260 Scott Frauenknecht
￼
dan7800 
￼
scioffi Stephen Cioffi
1. Start the application
2. Run through the first game
3. Start the second game
4. Color vision deficiency will not render

**Expected behavior**
All circles appear and change at all times and the controllers for changing the color vision deficiency work properly.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Safari

**Comment by akath20** [comment]
A video of this reproducing would be very helpful, along with your Safari version (in menu bar, Safari -> About) along with the build number of your operating system found at  -> System Preferences (the Version number and build number next to it)

**Comment by Boggartfly** [comment]
This now works.
