### ISSUE TITLE
Supplementary Materials Unreachable via /suppMaterials

### ISSUE THREAD

**Issue by saf6260** [all-rit/AccessibilityLab2#41]
**Describe the bug**
Supp Materials page unreachable by system after most recent update.

**To Reproduce**
1. Go to the website
2. Go to lab 2
3. Add /suppMaterials to the end of the link

**Expected behavior**
You should be redirected to the supplementary materials landing page

**Desktop (please complete the following information):**
All Systems/ browsers

**Additional context**
Steve you and I discussed this I just wanted to open an issue so it was on both of our radars

**Comment by scioffi** [comment]
![image](https://user-images.githubusercontent.com/2954285/54304687-10c3e880-459c-11e9-952e-a4f6e86b99b9.png)

Make sure your version is not cached.

**Comment by saf6260** [comment]
Sorry should've clarified. Local testing doesn't work for this

**Comment by saf6260** [comment]
Also, a local image on the case study page is not being sent up to the hosted page. Just getting the alt tag instead of the image
